run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - .*/
    - docs
  skip-dirs-use-default: true

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

output:
  format: colored-line-number 
