version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PROJECT_ID=${PROJECT_ID}
      - BUCKET_NAME=${BUCKET_NAME}
      - LOCATION=${LOCATION}
      - PORT=8080
      - DEBUG=true
    volumes:
      - .:/app
    command: ["go", "run", "./cmd/server"]

  test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: ["go", "test", "-v", "./..."] 
